name: Test and Deploy

on:
  pull_request_target:
    branches:
      - "*"

  # Allow Manual Runs
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: ./.github/actions/setup-repo
      - name: Static Analysis
        uses: ./.github/actions/static-analysis
